version: "3.9"
services: 
  bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    volumes: 
      - ./bot/db:/bot/db
      - ./bot/logs:/bot/logs
    ports: 
      - "9999:9999"
    environment:
      - OTP_CHECK_TOKEN=${OTP_CHECK_TOKEN}
    restart: always

  web:
    build: 
      context: ./www
      dockerfile: Dockerfile
    depends_on: 
      - bot
    volumes: 
      - ./bot/db:/www/db
    ports: 
      - "8080:8080"
    restart: always